# Generated by Django 3.2.25 on 2025-01-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['id'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
    ]
